export {
  ATTR_GEN_AI_OPERATION_NAME as SEMATTRS_GEN_AI_OPERATION_NAME,
  ATTR_GEN_AI_AGENT_ID as SEMATTRS_GEN_AI_AGENT_ID,
  ATTR_GEN_AI_AGENT_NAME as SEMATTRS_GEN_AI_AGENT_NAME,
  ATTR_GEN_AI_AGENT_DESCRIPTION as SEMATTRS_GEN_AI_AGENT_DESCRIPTION,
  ATTR_GEN_AI_CONVERSATION_ID as SEMATTRS_GEN_AI_CONVERSATION_ID,
  ATTR_GEN_AI_REQUEST_MODEL as SEMATTRS_GEN_AI_REQUEST_MODEL,
  ATTR_GEN_AI_REQUEST_TEMPERATURE as SEMATTRS_GEN_AI_REQUEST_TEMPERATURE,
  ATTR_GEN_AI_REQUEST_MAX_TOKENS as SEMATTRS_GEN_AI_REQUEST_MAX_TOKENS,
  ATTR_GEN_AI_RESPONSE_MODEL as SEMATTRS_GEN_AI_RESPONSE_MODEL,
  ATTR_GEN_AI_RESPONSE_ID as SEMATTRS_GEN_AI_RESPONSE_ID,
  ATTR_GEN_AI_RESPONSE_FINISH_REASONS as SEMATTRS_GEN_AI_RESPONSE_FINISH_REASONS,
  ATTR_GEN_AI_USAGE_INPUT_TOKENS as SEMATTRS_GEN_AI_USAGE_INPUT_TOKENS,
  ATTR_GEN_AI_USAGE_OUTPUT_TOKENS as SEMATTRS_GEN_AI_USAGE_OUTPUT_TOKENS,
  ATTR_GEN_AI_INPUT_MESSAGES as SEMATTRS_GEN_AI_INPUT_MESSAGES,
  ATTR_GEN_AI_OUTPUT_MESSAGES as SEMATTRS_GEN_AI_OUTPUT_MESSAGES,
  ATTR_GEN_AI_SYSTEM_INSTRUCTIONS as SEMATTRS_GEN_AI_SYSTEM_INSTRUCTIONS,
  ATTR_GEN_AI_TOOL_DEFINITIONS as SEMATTRS_GEN_AI_TOOL_DEFINITIONS,
  ATTR_GEN_AI_TOOL_NAME as SEMATTRS_GEN_AI_TOOL_NAME,
  ATTR_GEN_AI_TOOL_DESCRIPTION as SEMATTRS_GEN_AI_TOOL_DESCRIPTION,
  ATTR_GEN_AI_TOOL_CALL_ARGUMENTS as SEMATTRS_GEN_AI_TOOL_CALL_ARGUMENTS,
  ATTR_GEN_AI_TOOL_CALL_RESULT as SEMATTRS_GEN_AI_TOOL_CALL_RESULT,
  ATTR_GEN_AI_TOOL_CALL_ID as SEMATTRS_GEN_AI_TOOL_CALL_ID,
  ATTR_GEN_AI_PROVIDER_NAME as SEMATTRS_GEN_AI_PROVIDER_NAME,
  GEN_AI_OPERATION_NAME_VALUE_INVOKE_AGENT as GEN_AI_OPERATION_INVOKE_AGENT,
  GEN_AI_OPERATION_NAME_VALUE_EXECUTE_TOOL as GEN_AI_OPERATION_EXECUTE_TOOL,
  ATTR_ERROR_TYPE as SEMATTRS_ERROR_TYPE,
  ATTR_ENDUSER_ID as SEMATTRS_ENDUSER_ID,
  ATTR_SERVER_ADDRESS as SEMATTRS_SERVER_ADDRESS,
  ATTR_SERVER_PORT as SEMATTRS_SERVER_PORT,
} from '@opentelemetry/semantic-conventions/incubating';

export { ATTR_SERVER_ADDRESS, ATTR_SERVER_PORT } from '@opentelemetry/semantic-conventions';

export const GEN_AI_PROVIDER_DUST = 'dust';

export const SEMATTRS_GEN_AI_RETRIEVAL_DOCUMENTS = 'dust.retrieval.documents';
export const SEMATTRS_DUST_AGENT_VERSION = 'dust.agent.version';
export const SEMATTRS_DUST_AGENT_VERSION_CREATED_AT = 'dust.agent.version_created_at';

export const DUST_EVENT_GENERATION_TOKENS = 'generation_tokens';
export const DUST_EVENT_AGENT_ACTION_SUCCESS = 'agent_action_success';
export const DUST_EVENT_AGENT_MESSAGE_SUCCESS = 'agent_message_success';
export const DUST_EVENT_AGENT_ERROR = 'agent_error';
export const DUST_EVENT_USER_MESSAGE_ERROR = 'user_message_error';
